### ISSUE TITLE
error 'No value present' during connecting

### ISSUE THREAD

**Issue by varuzam** [akardapolov/ASH-Viewer#19]
![Screenshot_2019-04-26_00-55-24](https://user-images.githubusercontent.com/6206965/56771184-a6b77980-67be-11e9-838d-5f055b00ea7c.png)
Hello
Version 4.1.1
I can not to connect to postgres db.  All info are on screenshot

**Comment by akardapolov** [comment]
Hi, @varuzam 

Please run application using run.bat and past error log here.
Which version of Postgres db?

Thanks,
Alex.

**Comment by varuzam** [comment]
I use ubuntu.

openjdk version "1.8.0_191"

postgres jdbc driver from 
https://jdbc.postgresql.org/download/postgresql-42.2.5.jar

Error:
11:11:37.637 [Thread-5] ERROR remote.RemoteDBManager - ASH Viewer error: 
java.sql.SQLException: Cannot load JDBC driver class 'org.postgresql.Driver'
org.apache.commons.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:2001)
org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:1897)
org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1413)
remote.RemoteDBManager.getConnection(RemoteDBManager.java:50)
core.processing.GetFromRemoteAndStore.initializeConnection(GetFromRemoteAndStore.java:500)
core.processing.GetFromRemoteAndStore.initConnection(GetFromRemoteAndStore.java:102)
gui.connect.ConnectToDbArea.loadObjectsByConnectionName(ConnectToDbArea.java:449)
gui.util.ProgressBarUtil$1.run(ProgressBarUtil.java:79)

**Comment by Airell** [comment]
Using 4.1.1, I got a similar error for Oracle. I'm not sure it's the same cause, the stack trace might be different because of a different driver. Using ojdbc8.jar from 12.2 release.

08:31:00.140 [Thread-9] ERROR core.processing.GetFromRemoteAndStore - [core.processing.GetFromRemoteAndStore.loadSqlMetaData(GetFromRemoteAndStore.java:512), core.processing.GetFromRemoteAndStore.loadMetadata(GetFromRemoteAndStore.java:280), core.processing.GetFromRemoteAndStore.loadSqlsMetadata(GetFromRemoteAndStore.java:116), core.processing.GetFromRemoteAndStore.loadDataFromRemoteToLocalStore(GetFromRemoteAndStore.java:129), gui.connect.ConnectToDbArea.loadObjectsByConnectionName(ConnectToDbArea.java:457), gui.util.ProgressBarUtil$1.run(ProgressBarUtil.java:79)]
java.lang.NullPointerException
        at core.processing.GetFromRemoteAndStore.loadSqlMetaData(GetFromRemoteAndStore.java:512)
        at core.processing.GetFromRemoteAndStore.loadMetadata(GetFromRemoteAndStore.java:280)
        at core.processing.GetFromRemoteAndStore.loadSqlsMetadata(GetFromRemoteAndStore.java:116)
        at core.processing.GetFromRemoteAndStore.loadDataFromRemoteToLocalStore(GetFromRemoteAndStore.java:129)
        at gui.connect.ConnectToDbArea.loadObjectsByConnectionName(ConnectToDbArea.java:457)
        at gui.util.ProgressBarUtil$1.run(ProgressBarUtil.java:79)
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135)
        at core.processing.GetFromRemoteAndStore.getColumnIdForCol(GetFromRemoteAndStore.java:495)
        at core.processing.GetFromRemoteAndStore.lambda$loadSqlsMetadata$1(GetFromRemoteAndStore.java:123)
        at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at core.processing.GetFromRemoteAndStore.loadSqlsMetadata(GetFromRemoteAndStore.java:123)
        at core.processing.GetFromRemoteAndStore.loadDataFromRemoteToLocalStore(GetFromRemoteAndStore.java:129)
        at gui.connect.ConnectToDbArea.loadObjectsByConnectionName(ConnectToDbArea.java:457)
        at gui.util.ProgressBarUtil$1.run(ProgressBarUtil.java:79)
08:31:02.112 [AWT-EventQueue-1] INFO gui.actions.ConnectToDbAction - ConnectToDbAction button pressed

**Comment by feagor** [comment]
Get same issue when setting oracle connection.
Can you output original error message from oracle/postgre such as 'ORA-12541: TNS:no listener' or 'Invalid Login/pas', but not global 'No value present'.
Thank you

**Comment by akardapolov** [comment]
@feagor @Airell @varuzam 

It shows full stack trace in message dialog after error while connecting to remote database.

https://github.com/akardapolov/ASH-Viewer/commit/82c8c07939c279e9d91af38584ccde25bb5e47d5

**Comment by catmater** [comment]
Same issue under macos, in version  4.2.2 , after pressing connect - have this error:

ASH Viewer error: java.sql.SQLException: Cannot load JDBC driver class 'oracle.jdbc.driver.OracleDriver'
org.apache.commons.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:2001)
org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:1897)
org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1413)
remote.RemoteDBManager.getConnection(RemoteDBManager.java:47)
core.processing.GetFromRemoteAndStore.initializeConnection(GetFromRemoteAndStore.java:528)
core.processing.GetFromRemoteAndStore.initConnection(GetFromRemoteAndStore.java:102)
gui.connect.ConnectToDbArea.loadObjectsByConnectionName(ConnectToDbArea.java:488)
gui.util.ProgressBarUtil$1.run(ProgressBarUtil.java:79)

trying to load with a different lib (ojdbc6.jar - ojdbc10.jar) , have same error. ASH Viewer 3.3.75 work fine.

**Comment by akardapolov** [comment]
Hi!

@varuzam @catmater @feagor try it out https://github.com/akardapolov/ASH-Viewer/commit/6916bfce6a3505ae6337cc456d75f748ad97f3d3

Bin files with fixes here: https://github.com/akardapolov/ASH-Viewer/releases/tag/v4.2.3

Thanks,
Alex.

**Comment by catmater** [comment]
@akardapolov , fanx, under macos working now!!

**Comment by Paulpatou** [comment]
Hi
I have same issue on Windows 10 ( java 1.8.0_231) and Ubuntu 18 (openjdk version 1.8.0_222) :
ASH-Viewer:4.2.4
Driver JDBC Postgresql :  42.2.8

error ubuntu =>
`16:56:29.450 [main] INFO Main - Start application
16:56:30.277 [main] INFO gui.BasicFrame - Start instantiating new BasicFrame
16:56:31.079 [main] INFO gui.actions.ConnectToDbAction - ConnectToDbAction button pressed
16:56:35.321 [Thread-4] ERROR core.processing.GetFromRemoteAndStore - [org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497), org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233), org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310), org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446), org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370), org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:311), org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:297), org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:274), org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225), org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:203), org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:203), core.processing.GetFromRemoteAndStore.loadSqlMetaData(GetFromRemoteAndStore.java:539), core.processing.GetFromRemoteAndStore.loadMetadata(GetFromRemoteAndStore.java:283), core.processing.GetFromRemoteAndStore.loadSqlsMetadata(GetFromRemoteAndStore.java:116), core.processing.GetFromRemoteAndStore.loadDataFromRemoteToLocalStore(GetFromRemoteAndStore.java:126), gui.connect.ConnectToDbArea.loadObjectsByConnectionName(ConnectToDbArea.java:496), gui.util.ProgressBarUtil$1.run(ProgressBarUtil.java:79)]
org.postgresql.util.PSQLException: ERREUR: la colonne « backend_type » n'existe pas
  Position : 192
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:311)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:297)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:274)
        at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:225)
        at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:203)
        at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:203)
        at core.processing.GetFromRemoteAndStore.loadSqlMetaData(GetFromRemoteAndStore.java:539)
        at core.processing.GetFromRemoteAndStore.loadMetadata(GetFromRemoteAndStore.java:283)
        at core.processing.GetFromRemoteAndStore.loadSqlsMetadata(GetFromRemoteAndStore.java:116)
        at core.processing.GetFromRemoteAndStore.loadDataFromRemoteToLocalStore(GetFromRemoteAndStore.java:126)
        at gui.connect.ConnectToDbArea.loadObjectsByConnectionName(ConnectToDbArea.java:496)
        at gui.util.ProgressBarUtil$1.run(ProgressBarUtil.java:79)
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135)
        at core.processing.GetFromRemoteAndStore.getColumnIdForCol(GetFromRemoteAndStore.java:525)
        at core.processing.GetFromRemoteAndStore.lambda$loadSqlsMetadata$0(GetFromRemoteAndStore.java:120)
        at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
        at core.processing.GetFromRemoteAndStore.loadSqlsMetadata(GetFromRemoteAndStore.java:120)
        at core.processing.GetFromRemoteAndStore.loadDataFromRemoteToLocalStore(GetFromRemoteAndStore.java:126)
        at gui.connect.ConnectToDbArea.loadObjectsByConnectionName(ConnectToDbArea.java:496)
        at gui.util.ProgressBarUtil$1.run(ProgressBarUtil.java:79)`

**Comment by akardapolov** [comment]
@Paulpatou 

Hi! 
What is the version of Postgresql DB?

Post here describe output of **pg_stat_activity** table.

http://www.postgresqltutorial.com/postgresql-describe-table/

Thanks,
Alex.

**Comment by Paulpatou** [comment]
Hi, I use Postgresql 9.4
Output =>
1/
16516,"database_name",15603,2795571,"paul","PostgreSQL JDBC Driver","ip_client",NULL,33096,"2019-11-25 10:14:02.200861+01",NULL,"2019-11-25 10:14:02.231097+01","2019-11-25 10:14:02.23111+01",False,"idle",NULL,NULL,"SET application_name = 'PostgreSQL JDBC Driver'"


2/
16516,"database_name",15604,2795571,"paul","PostgreSQL JDBC Driver","ip_client",NULL,33098,"2019-11-25 10:14:02.233606+01",NULL,"2019-11-25 10:14:02.613549+01","2019-11-25 10:14:02.619423+01",False,"idle",NULL,NULL,"SELECT current_timestamp as SAMPLE_TIME, datid, datname, pid AS SESSION_ID, pid AS SESSION_SERIAL, usesysid AS USER_ID, coalesce(usename, 'unknown') as usename, concat(application_name,'::', backend_type, '::', coalesce(client_hostname, client_addr::text, 'localhost')) AS PROGRAM, wait_event_type AS WAIT_CLASS, wait_event AS EVENT, query, substring(md5(query) from 0 for 15) AS SQL_ID, left(query, strpos(query, ' '))  AS SQL_OPNAME, coalesce(query_start, xact_start, backend_start) as query_start, 1000 * EXTRACT(EPOCH FROM (clock_timestamp()-coalesce(query_start, xact_start, backend_start))) as duration from pg_stat_activity where state='active' and pid != pg_backend_pid()"

**Comment by akardapolov** [comment]
@Paulpatou 
Hi!

Use postgres96 profile in connection settings: https://github.com/akardapolov/ASH-Viewer/blob/master/media/connection.png

See the error text: ERROR: column "backend_type" does not exist Position

Code has not contains backend_type column: https://github.com/akardapolov/ASH-Viewer/blob/master/ashv/src/main/java/profile/Postgres96.java

Thanks,
Alex.
