### ISSUE TITLE
NPE while loading raw data in offline mode

### ISSUE THREAD

**Issue by akardapolov** [akardapolov/ASH-Viewer#26]
> Exception in thread "Thread-9" java.lang.NullPointerException
	at store.DatabaseDAO.lambda$getMatrixDataForJTable$1(DatabaseDAO.java:116)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at store.DatabaseDAO.getMatrixDataForJTable(DatabaseDAO.java:114)
	at gui.table.RawDataTable.loadDataToTableModel(RawDataTable.java:220)
	at gui.table.RawDataTable.access$400(RawDataTable.java:33)
	at gui.table.RawDataTable$1.run(RawDataTable.java:127)

**Comment by akardapolov** [comment]
Done https://github.com/akardapolov/ASH-Viewer/commit/32284c9e6892be2e32bd4995b2f1055c2f5d28cb
