### ISSUE TITLE
Совсем не работает 

### ISSUE THREAD

**Issue by arkanovas** [akardapolov/ASH-Viewer#33]
После того, как делаю конфиг, сразу же падает. после этого вообще не запускается.
Если конфиг убрать, то сразу же запускается.
конфиг
```
!!config.profile.ConfigProfile
configName: maindb
connProfile: {connName: maindb, driver: oracle.jdbc.driver.OracleDriver, jar: 'D:\Distrib\СУБД\ashv-4-bin\lib\ojdbc6.jar',
  password: XXX, profileName: OracleEE, url: 'jdbc:oracle:thin:@db.XXX.ru:1521:MAIN',
  userName: arkanovas}
olapRetainDays: 101
rawRetainDays: 101
running: false
sqlColProfileList: null
```

```
D:\Distrib\СУБД\ashv-4>"C:\Program Files (x86)\Java\jre1.8.0_211\bin\java.exe" -Xmx1024m -jar ASH-Viewer.jar 
03.04.20 12:44:23.290 [main] INFO Main - Start application
03.04.20 12:44:23.492 [main] INFO BasicFrame - Start instantiating new BasicFrame 
Exception in thread "main" org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
    at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:218) 
    at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176) 
    at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171) 
    at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126) 
    at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1177) 
    at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:287) 
    at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) 
    at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:195) 
    at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) 
    at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) 
    at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:107) 
    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:141) 
    at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525) 
    at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:519) 
    at config.yaml.YamlConfig.loadConfigurationFile(YamlConfig.java:73) 
    at config.yaml.YamlConfig.lambda$loadConfigsFromFs$0(YamlConfig.java:61) 
    at java.util.ArrayList.forEach(Unknown Source) 
    at config.yaml.YamlConfig.loadConfigsFromFs(YamlConfig.java:58) 
    at config.yaml.YamlConfig.<init>(YamlConfig.java:35) 
    at config.yaml.YamlConfig_Factory.newInstance(YamlConfig_Factory.java:45) 
    at config.yaml.YamlConfig_Factory.get(YamlConfig_Factory.java:35) 
    at config.yaml.YamlConfig_Factory.get(YamlConfig_Factory.java:11) 
    at dagger.internal.DoubleCheck.get(DoubleCheck.java:47) 
    at core.manager.ConfigurationManager_Factory.get(ConfigurationManager_Factory.java:36) 
    at core.manager.ConfigurationManager_Factory.get(ConfigurationManager_Factory.java:11) 
    at dagger.internal.DoubleCheck.get(DoubleCheck.java:47) 
    at gui.actions.ConnectToDbAction_Factory.get(ConnectToDbAction_Factory.java:35) 
    at gui.actions.ConnectToDbAction_Factory.get(ConnectToDbAction_Factory.java:10) 
    at dagger.internal.DoubleCheck.get(DoubleCheck.java:47) 
    at gui.MainWindow_Factory.get(MainWindow_Factory.java:62) 
    at gui.MainWindow_Factory.get(MainWindow_Factory.java:13) 
    at dagger.internal.DoubleCheck.get(DoubleCheck.java:47) 
    at config.dagger.DaggerMainComponent.createMainWindow(DaggerMainComponent.java:205) 
    at Main.main(Main.java:16) 
Caused by: java.nio.charset.MalformedInputException: Input length = 1 
    at java.nio.charset.CoderResult.throwException(Unknown Source) 
    at sun.nio.cs.StreamDecoder.implRead(Unknown Source) 
    at sun.nio.cs.StreamDecoder.read(Unknown Source) 
    at java.io.InputStreamReader.read(Unknown Source) 
    at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:125) 
    at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:183) 
    ... 33 more 
```

**Comment by akardapolov** [comment]
Здравствуйте!

А вы правили конфигурационный файл вручную или через интерфейс?

**Comment by akardapolov** [comment]
>> 'D:\Distrib\СУБД\ashv-4-bin\lib\ojdbc6.jar'

Похоже проблема в русском наименовании директории, видимо Yaml не поддерживает интернационализацию. Аналогичная проблема описана [здесь](https://www.spigotmc.org/threads/my-plugin-yml-is-broken.304871/?__cf_chl_jschl_tk__=b404d5802229a966f4aa975ae5ff163cdc14556f-1585905179-0-Af6HnkGdmqwkmhE1pREyHDrMG4LCHGMLsAMGVOEN7tbee3ocm9oBgKhCDzsJGtxah6SQrZXyTqrEI2x38jlliALFCpvbVmhypdli1g0k3-rMfqfFQAJIbGiviktr3ooL48uZUCXdMi6vYbITKZhuf_N84C18gu6frsU1M2tYIP1A-FRfnYzDeN2ePdeYExLJ8oe1Nbdkqlkp8cDopy_U0xNzR-C4i2s6rR_nk9sZOWn5yzlNV5F0-DCylec9oeLhZhLirxaHw9CcHSwjLyImytQMPEcol5ghb9AXsJCg0fYNeSuqCPDGmOfo1v0bTBQH1yvV3E4nJJFa7dpJIPhS6g4)

Как решение - не использовать русские названия в директориях

**Comment by arkanovas** [comment]
Да, проблема была именно в русском названии, я еще подумал об этом и программу перенес в каталог без русских символов, а конфиг забыл с нуля создать и в нем остались русские символы.
Спасибо большое, буду пользовать теперь. Стоит это прямо где-то прописать на экране создания соединения или в readme каком-то.
