### ISSUE TITLE
Error java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by nick0lay01** [akardapolov/ASH-Viewer#49]
Hi.

During making connection to one of my Oracle databases 19c, getting error:

```
19.06.21 14:05:55.095 [main] INFO  Main - Start application
19.06.21 14:05:55.688 [main] INFO  BasicFrame - Start instantiating new BasicFrame
19.06.21 14:06:00.299 [main] INFO  ConnectToDbAction - ConnectToDbAction button pressed
19.06.21 14:06:23.318 [Thread-2] INFO  GetFromRemoteAndStore - Start loading
19.06.21 14:06:23.433 [Thread-2] INFO  GetFromRemoteAndStore - Start loading olap
19.06.21 14:06:29.157 [Thread-2] INFO  GetFromRemoteAndStore - Start loading stacked chart
java.lang.ArrayIndexOutOfBoundsException: Index 50 out of bounds for length 50
        at org.jfree.data.extension.impl.XYDatasetSelectionExtension.initSelection(XYDatasetSelectionExtension.java:142)
        at org.jfree.data.extension.impl.XYDatasetSelectionExtension.datasetChanged(XYDatasetSelectionExtension.java:111)
        at org.jfree.data.general.AbstractDataset.notifyListeners(AbstractDataset.java:189)
        at org.jfree.data.general.AbstractDataset.fireDatasetChanged(AbstractDataset.java:172)
        at org.jfree.data.xy.CategoryTableXYDataset.add(CategoryTableXYDataset.java:118)
        at gui.chart.CategoryTableXYDatasetRDA.addSeriesValue(CategoryTableXYDatasetRDA.java:34)
        at core.processing.GetFromRemoteAndStore.lambda$null$8(GetFromRemoteAndStore.java:252)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at core.processing.GetFromRemoteAndStore.lambda$null$9(GetFromRemoteAndStore.java:249)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at core.processing.GetFromRemoteAndStore.lambda$loadToMainStackedChart$10(GetFromRemoteAndStore.java:247)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at core.processing.GetFromRemoteAndStore.loadToMainStackedChart(GetFromRemoteAndStore.java:247)
        at core.processing.GetFromRemoteAndStore.loadDataFromRemoteToLocalStore(GetFromRemoteAndStore.java:152)
        at gui.connect.ConnectToDbArea.loadObjectsByConnectionName(ConnectToDbArea.java:514)
        at gui.util.ProgressBarUtil$1.run(ProgressBarUtil.java:79)
19.06.21 14:06:46.965 [pool-2-thread-1] INFO  GetFromRemoteAndStore - Start loading
19.06.21 14:06:47.048 [pool-2-thread-1] INFO  GetFromRemoteAndStore - Start loading olap
19.06.21 14:06:48.117 [pool-2-thread-1] INFO  GetFromRemoteAndStore - Start loading stacked chart
java.lang.ArrayIndexOutOfBoundsException
19.06.21 14:06:54.237 [pool-2-thread-1] INFO  GetFromRemoteAndStore - Start loading
19.06.21 14:06:54.328 [pool-2-thread-1] INFO  GetFromRemoteAndStore - Start loading olap
19.06.21 14:06:55.254 [pool-2-thread-1] INFO  GetFromRemoteAndStore - Start loading stacked chart
java.lang.ArrayIndexOutOfBoundsException
19.06.21 14:07:00.995 [pool-2-thread-1] INFO  GetFromRemoteAndStore - Start loading
19.06.21 14:07:01.093 [pool-2-thread-1] INFO  GetFromRemoteAndStore - Start loading olap
19.06.21 14:07:01.654 [pool-2-thread-1] INFO  GetFromRemoteAndStore - Start loading stacked chart
java.lang.ArrayIndexOutOfBoundsException
19.06.21 14:07:07.236 [pool-2-thread-1] INFO  GetFromRemoteAndStore - Start loading
19.06.21 14:07:07.318 [pool-2-thread-1] INFO  GetFromRemoteAndStore - Start loading olap
19.06.21 14:07:07.647 [pool-2-thread-1] INFO  GetFromRemoteAndStore - Start loading stacked chart
```

Mac OS 10.15.7

ashv version is 3.5.1

$ $JAVA_EXE -version
java version "11.0.6" 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)

**Comment by nick0lay01** [comment]
After  the error the chart is empty. And there is not ability to make it work.
During ashv restart - the same picture.

![image_2021-06-21_15-42-01](https://user-images.githubusercontent.com/86153997/122763791-69b87600-d2a7-11eb-8a12-7ebce97fe97c.png)

**Comment by akardapolov** [comment]
Hi!

Could you try the new build: ashv-3.5.1.1-bin.zip
https://github.com/akardapolov/ASH-Viewer/releases/tag/v3.5.1

Thanks,
Alex.

**Comment by nick0lay01** [comment]
Works great! No issues at all! I ran it several times.
