### ISSUE TITLE
При попытке конекта получаю Cannot load JDBC driver class 'oracle.jdbc.driver.OracleDriver'

### ISSUE THREAD

**Issue by slavadba** [akardapolov/ASH-Viewer#68]
При попытке конекта получаю ошибки:

22.12.22 10:26:18.532 [main] INFO  Main - Start application
22.12.22 10:26:18.936 [main] INFO  BasicFrame - Start instantiating new BasicFrame
22.12.22 10:26:20.742 [main] INFO  ConnectToDbAction - ConnectToDbAction button pressed
Cannot load JDBC driver class 'oracle.jdbc.driver.OracleDriver'
java.lang.ClassNotFoundException: oracle.jdbc.driver.OracleDriver
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.apache.commons.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:1992)
        at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:1897)
        at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1413)
        at remote.RemoteDBManager.getConnection(RemoteDBManager.java:54)
        at core.processing.GetFromRemoteAndStore.initializeConnection(GetFromRemoteAndStore.java:578)
        at core.processing.GetFromRemoteAndStore.initConnection(GetFromRemoteAndStore.java:134)
        at gui.connect.ConnectToDbArea.loadObjectsByConnectionName(ConnectToDbArea.java:594)
        at gui.util.Progres22.12.22 10:26:30.248 [Thread-1] ERROR ConnectToDbArea - ASH Viewer error: java.sql.SQLException: Cannot load JDBC driver class 'oracle.jdbc.driver.OracleDriver'
org.apache.commons.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:2001)
org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:1897)
org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1413)
remote.RemoteDBManager.getConnection(RemoteDBManager.java:54)
core.processing.GetFromRemoteAndStore.initializeConnection(GetFromRemoteAndStore.java:578)
core.processing.GetFromRemoteAndStore.initConnection(GetFromRemoteAndStore.java:134)
gui.connect.ConnectToDbArea.loadObjectsByConnectionName(ConnectToDbArea.java:594)
gui.util.ProgressBarUtil$1.run(ProgressBarUtil.java:79)

содержимое run.bat:

SET JAVA_HOME=C:\Program Files\Java\jdk-19
SET JAVA_EXE="%JAVA_HOME%\bin\java.exe"
%JAVA_EXE% -Xmx1024m -jar ASH-Viewer.jar

как выглядят параметры конекта https://ibb.co/fF6rCFK

**Comment by akardapolov** [comment]
Привет!

Подключаетесь к Postgres, судя по URL, а профиль Oracle. Надо выбрать профиль один из Postgres*
https://ibb.co/fF6rCFK

Thanks,
Alex.

**Comment by slavadba** [comment]
А что значит "выбрать профиль один из Postgres*" ? если имеется ввиду поле Name в котором проставлено Oracle EE - то оно не редактируемое, это видно на скриншоте.

**Comment by akardapolov** [comment]
Когда создаете подключение - надо выбрать соответствующий профиль, после редактирование недоступно.

В данном случае можно закрыть программу, открыть заново и сделать копию профиля и в нем поменять значение.

**Comment by slavadba** [comment]
Спасибо большое за помощь!

**Comment by slavadba** [comment]
Спасибо большое за помощь!
