### ISSUE TITLE
ASH Viewer error: java.util.NoSuchElementException: No value present при подключению к Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

### ISSUE THREAD

**Issue by yditr** [akardapolov/ASH-Viewer#78]
15.07.24 18:40:20.782 [main] INFO  ConnectToDbAction - ConnectToDbAction button pressed
15.07.24 18:40:53.956 [Thread-5] ERROR GetFromRemoteAndStore - [oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494), oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446), oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054), oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623), oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252), oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612), oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:213), oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:37), oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:733), oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:904), oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1082), oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1276), oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:366), org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:203), org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:203), core.processing.GetFromRemoteAndStore.loadSqlMetaData(GetFromRemoteAndStore.java:589), core.processing.GetFromRemoteAndStore.loadMetadata(GetFromRemoteAndStore.java:316), core.processing.GetFromRemoteAndStore.loadSqlsMetadata(GetFromRemoteAndStore.java:145), core.processing.GetFromRemoteAndStore.loadDataFromRemoteToLocalStore(GetFromRemoteAndStore.java:156), gui.connect.ConnectToDbArea.loadObjectsByConnectionName(ConnectToDbArea.java:602), gui.util.ProgressBarUtil$1.run(ProgressBarUtil.java:79)]
java.sql.SQLSyntaxErrorException: ORA-00942: таблица или представление пользователя не существует

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:213)
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:37)
        at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:733)
        at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:904)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1082)
        at oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1276)
        at oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:366)
        at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:203)
        at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:203)
        at core.processing.GetFromRemoteAndStore.loadSqlMetaData(GetFromRemoteAndStore.java:589)
        at core.processing.GetFromRemoteAndStore.loadMetadata(GetFromRemoteAndStore.java:316)
        at core.processing.GetFromRemoteAndStore.loadSqlsMetadata(GetFromRemoteAndStore.java:145)
        at core.processing.GetFromRemoteAndStore.loadDataFromRemoteToLocalStore(GetFromRemoteAndStore.java:156)
        at gui.connect.ConnectToDbArea.loadObjectsByConnectionName(ConnectToDbArea.java:602)
        at gui.util.ProgressBarUtil$1.run(ProgressBarUtil.java:79)
Caused by: Error : 942, Position : 62, Sql = select a.*, b.object_name, b.object_type, subobject_name from v$active_session_history a, all_objects b where a.current_obj# = b.object_id(+) and rownum = 1, OriginalSql = select a.*, b.object_name, b.object_type, subobject_name from v$active_session_history a, all_objects b where a.current_obj# = b.object_id(+) and rownum = 1, Error Msg = ORA-00942: таблица или представление пользователя не существует

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
        ... 20 more
15.07.24 18:40:54.270 [Thread-5] ERROR GetFromRemoteAndStore - [oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494), oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446), oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054), oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623), oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252), oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612), oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:213), oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:37), oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:733), oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:904), oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1082), oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1276), oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:366), org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:203), org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:203), core.processing.GetFromRemoteAndStore.loadSqlMetaData(GetFromRemoteAndStore.java:589), core.processing.GetFromRemoteAndStore.loadMetadata(GetFromRemoteAndStore.java:319), core.processing.GetFromRemoteAndStore.loadSqlsMetadata(GetFromRemoteAndStore.java:145), core.processing.GetFromRemoteAndStore.loadDataFromRemoteToLocalStore(GetFromRemoteAndStore.java:156), gui.connect.ConnectToDbArea.loadObjectsByConnectionName(ConnectToDbArea.java:602), gui.util.ProgressBarUtil$1.run(ProgressBarUtil.java:79)]
java.sql.SQLSyntaxErrorException: ORA-00942: таблица или представление пользователя не существует

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:213)
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:37)
        at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:733)
        at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:904)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1082)
        at oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1276)
        at oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:366)
        at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:203)
        at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:203)
        at core.processing.GetFromRemoteAndStore.loadSqlMetaData(GetFromRemoteAndStore.java:589)
        at core.processing.GetFromRemoteAndStore.loadMetadata(GetFromRemoteAndStore.java:319)
        at core.processing.GetFromRemoteAndStore.loadSqlsMetadata(GetFromRemoteAndStore.java:145)
        at core.processing.GetFromRemoteAndStore.loadDataFromRemoteToLocalStore(GetFromRemoteAndStore.java:156)
        at gui.connect.ConnectToDbArea.loadObjectsByConnectionName(ConnectToDbArea.java:602)
        at gui.util.ProgressBarUtil$1.run(ProgressBarUtil.java:79)
Caused by: Error : 942, Position : 62, Sql = select a.*, b.object_name, b.object_type, subobject_name from v$active_session_history a, all_objects b where a.current_obj# = b.object_id(+) and rownum = 1, OriginalSql = select a.*, b.object_name, b.object_type, subobject_name from v$active_session_history a, all_objects b where a.current_obj# = b.object_id(+) and rownum = 1, Error Msg = ORA-00942: таблица или представление пользователя не существует

        at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
        ... 20 more
15.07.24 18:40:54.282 [Thread-5] ERROR ConnectToDbArea - ASH Viewer error: java.util.NoSuchElementException: No value present
java.util.Optional.get(Unknown Source)
core.processing.GetFromRemoteAndStore.getColumnIdForCol(GetFromRemoteAndStore.java:574)
core.processing.GetFromRemoteAndStore.lambda$loadSqlsMetadata$52(GetFromRemoteAndStore.java:149)
java.util.LinkedList$LLSpliterator.forEachRemaining(Unknown Source)
java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
core.processing.GetFromRemoteAndStore.loadSqlsMetadata(GetFromRemoteAndStore.java:149)
core.processing.GetFromRemoteAndStore.loadDataFromRemoteToLocalStore(GetFromRemoteAndStore.java:156)
gui.connect.ConnectToDbArea.loadObjectsByConnectionName(ConnectToDbArea.java:602)
gui.util.ProgressBarUtil$1.run(ProgressBarUtil.java:79)
Using ashv-4.3.3 version

**Comment by yditr** [comment]
Пробовал на версиях 4.3.3.1, 4.3.3, 4.3.0, 4.2.3

**Comment by yditr** [comment]
На версии 4.4.1 такая де проблема у пользователя есть привилегии SYSDBA и запрос через sqlplus выполняется

**Comment by yditr** [comment]
Проблема решилась созданием нескольких пользователей отдельно для ASH viewer и создания таблиц.
