### ISSUE TITLE
NumberFormatException: For input string

### ISSUE THREAD

**Issue by gschindl216** [akardapolov/ASH-Viewer#80]
In our postgres-database we have very big pg_user.usesysid (ex. 2375421138) .

java.lang.NumberFormatException: For input string: "2375421138"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:588)
        at java.base/java.lang.Integer.valueOf(Integer.java:935)
        at gui.gantt.GanttDataById2.loadDataByRow(GanttDataById2.java:229)
        at gui.gantt.GanttDataById2.lambda$getDataToGantt$7(GanttDataById2.java:207)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:557)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611)
        at gui.gantt.GanttDataById2.getDataToGantt(GanttDataById2.java:200)
        at gui.gantt.MonitorGantt2.getGanttDataToViewSession(MonitorGantt2.java:157)
        at gui.gantt.MonitorGantt2.addGanttTablesToJPanel(MonitorGantt2.java:192)
        at gui.gantt.MonitorGantt2.loadDataToJPanelsPrivate0(MonitorGantt2.java:128)
        at gui.gantt.MonitorGantt2$1.run(MonitorGantt2.java:75)

**Comment by gschindl216** [comment]
Our Server: PostgreSQL 15.6
